# Generated by Django 4.1.7 on 2024-03-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_order', '0005_alter_order_payment_status_alter_order_used_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('failed', 'Failed'), ('completed', 'Completed'), ('pending', 'Pending')], max_length=20),
        ),
    ]
