# Generated by Django 4.1.7 on 2023-04-01 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('username', models.EmailField(max_length=240)),
                ('password', models.CharField(max_length=100)),
                ('Confirm_password', models.CharField(max_length=100)),
            ],
        ),
    ]
