# Generated by Django 4.1.7 on 2023-04-01 05:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=6),
        ),
        migrations.AddField(
            model_name='product',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='make',
            field=models.CharField(choices=[('BATA', 'Bata'), ('ADIDAS', 'Adidas'), ('PUMA', 'Puma'), ('REEBOK', 'Reebok'), ('NIKE', 'Nike'), ('WOODLAND', 'Woodland'), ('RED_CHIEF', 'Red Chief'), ('LEE_COOPER', 'Lee Cooper'), ('FILA', 'Fila'), ('SKECHERS', 'Skechers'), ('CONVERSE', 'Converse'), ('CLARKS', 'Clarks'), ('CROCS', 'Crocs'), ('HUSH_PUPPIES', 'Hush Puppies'), ('LIBERTY', 'Liberty'), ('SPARX', 'Sparx'), ('ACTION', 'Action'), ('LANCER', 'Lancer'), ('LOTTO', 'Lotto'), ('MOCHI', 'Mochi')], max_length=255),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stores.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='stores.product')),
            ],
            options={
                'unique_together': {('product', 'size')},
            },
        ),
    ]
